---
addons:
  apt:
    packages:
      - codespell
      - make
      - perl
      - shellcheck
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.oftc.net#munin"
    template:
      - "%{repository} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details: %{build_url}"

script:
  - make lint
  - make spelling
  - make test
